name: Replacer
on: push
jobs:
  Replace:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "udB.get(.*)"
          replace: "udB.get_key(.*)"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: dev
          title: "Jaamdu"
          token: {{ secrets.GH_TOKEN }}
